"""graph schema: nodes edges chunks runs

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-13
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=True),
        sa.Column("head_commit", sa.String(length=40), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CLONING", "PARSING", "INDEXED", "FAILED", name="repo_status"),
            nullable=False,
        ),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("index_cost_usd", sa.Float(), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repos")),
        sa.UniqueConstraint("url", "head_commit", name="uq_repos_url_commit"),
    )
    op.create_table(
        "index_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind", sa.Enum("FULL", "INCREMENTAL", "ESCALATION", name="run_kind"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", name="run_status"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_index_runs_repo_id_repos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_runs")),
    )
    op.create_index("ix_index_runs_repo", "index_runs", ["repo_id"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "REPO",
                "PACKAGE",
                "FILE",
                "CLASS",
                "FUNCTION",
                "METHOD",
                "CONFIG",
                "DOC",
                "TEST",
                name="node_kind",
            ),
            nullable=False,
        ),
        sa.Column("fqname", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("docstring", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("annotations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_nodes_repo_id_repos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
        sa.UniqueConstraint("repo_id", "fqname", name="uq_nodes_repo_fqname"),
    )
    op.create_index(
        "ix_nodes_repo_content_hash", "nodes", ["repo_id", "content_hash"], unique=False
    )
    op.create_index("ix_nodes_repo_kind", "nodes", ["repo_id", "kind"], unique=False)
    op.create_index("ix_nodes_repo_path", "nodes", ["repo_id", "path"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_chunks_node_id_nodes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_chunks_repo_id_repos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
    )
    op.create_index("ix_chunks_node", "chunks", ["node_id"], unique=False)
    op.create_index("ix_chunks_repo", "chunks", ["repo_id"], unique=False)
    op.create_table(
        "edges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("src_node_id", sa.BigInteger(), nullable=False),
        sa.Column("dst_node_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "CONTAINS", "IMPORTS", "CALLS", "INHERITS", "IMPLEMENTS", "TESTS", name="edge_kind"
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_edges_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["dst_node_id"],
            ["nodes.id"],
            name=op.f("fk_edges_dst_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"], ["repos.id"], name=op.f("fk_edges_repo_id_repos"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["src_node_id"],
            ["nodes.id"],
            name=op.f("fk_edges_src_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edges")),
        sa.UniqueConstraint("src_node_id", "dst_node_id", "kind", name="uq_edges_src_dst_kind"),
    )
    op.create_index("ix_edges_dst", "edges", ["dst_node_id"], unique=False)
    op.create_index("ix_edges_repo_kind", "edges", ["repo_id", "kind"], unique=False)
    op.create_index("ix_edges_src", "edges", ["src_node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_edges_src", table_name="edges")
    op.drop_index("ix_edges_repo_kind", table_name="edges")
    op.drop_index("ix_edges_dst", table_name="edges")
    op.drop_table("edges")
    op.drop_index("ix_chunks_repo", table_name="chunks")
    op.drop_index("ix_chunks_node", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_nodes_repo_path", table_name="nodes")
    op.drop_index("ix_nodes_repo_kind", table_name="nodes")
    op.drop_index("ix_nodes_repo_content_hash", table_name="nodes")
    op.drop_table("nodes")
    op.drop_index("ix_index_runs_repo", table_name="index_runs")
    op.drop_table("index_runs")
    op.drop_table("repos")
    # ### end Alembic commands ###

    # Drop the native enum types explicitly — Postgres keeps them after the
    # tables are dropped, which would break a re-up of this migration.
    for enum_name in ("edge_kind", "node_kind", "run_status", "run_kind", "repo_status"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
